### ISSUE TITLE
confusing message when arguments specified incorrectly

### ISSUE THREAD

**Issue by kaymccormick** [resurrecting-open-source-projects/packit#11]
Use case: "Oh, I am reading the manual page and I see I can use "-c 1" to get one packet. Let's try it..."

packit -c 1 -m capture "not port ssh"

Error: No destination IP address defined

Expected result:

An error message with more information on the problem in the arguments.

**Comment by davidpolverari** [comment]
Actually, the order in which you are specifying the mode and the rest of the options oppose the required order presented on packit's help and man page:

From packit help:
```
usage: packit -m mode [-options] 'expression'

Mode:
  -m mode     Runtime mode (Default: injection)
```
From packit man page:
```
Packet capture:

         packit -m capture [-cGHnvsX] [-i interface] [-r|-w file] expression

       Packet injection:

         packit -m inject [-t protocol] [-aAbcCdDeFgGhHjJkKlLmMnNoOpPqQrRsSTuUvwWxXyYzZ] [-i interface]
```

From those resources, we can see that using `-m mode` is mandatory _as the first argument_ if you want to use another mode than the default (injection). While that may seem somewhat arbitrary, it actually results from the combination of the peculiarities of the function used by packit to parse command-line option (`getopt`) and the way packit reuses some options letters according to the mode used and other variables. So, the example you provided is using the `inject` mode, as the `-m` option wasn't provided as the first argument, and the error message is correct, as an IP address would be required in this case and it wasn't provided.

Unfortunately, because of the command-line parsing implementation, the only other error message that could provide more context in the case you stated would probably be one that complained about you providing a string instead of a number as an argument to the `-m` option (the ICMPv4 TTL).
