### ISSUE TITLE
Cannot inject packets in Monitor Mode

### ISSUE THREAD

**Issue by dayrenefrometa** [resurrecting-open-source-projects/packit#21]
Hi, I have been using packit to inject UDP packets through a wireless interface and it works fine while the interface operates in Managed mode (it acts as a WiFi STA associated with an AP). To check it is working fine, I am capturing the injected packets with Wireshark on a different PC.

However,  I do need to operate the interface in Monitor mode and packit doesn't seem to work in this mode (I can no longer receive the injected packets when using Wireshark).

My question is if packit should work in Monitor mode, and if so, is it required additional configuration for the wireless interface to make it work?

Thank you very much in advance for your help.

Sincerely,

Dayrene

**Comment by sbirmi** [comment]
Not sure if I can solve your problem just yet but a few more details would
help. Can you describe your hardware (which wifi chipset and driver are you
using)? What steps did you use to put the interface in monitor mode? How
are you invoking UDP packet injection?

**Comment by davidpolverari** [comment]
Hi Dayrene!

> Hi, I have been using packit to inject UDP packets through a wireless interface and it works fine while the interface operates in Managed mode (it acts as a WiFi STA associated with an AP). To check it is working fine, I am capturing the injected packets with Wireshark on a different PC.
> 
> However, I do need to operate the interface in Monitor mode and packit doesn't seem to work in this mode (I can no longer receive the injected packets when using Wireshark).
> 
> My question is if packit should work in Monitor mode, and if so, is it required additional configuration for the wireless interface to make it work?

Some adapters are known for not allowing for packet injection, even though they can go into monitor mode.

That said, AFAIK `packit` will not work with wireless packet injection, because it uses `libnet` for the injection part and that library doesn't support it [^1]. There's a complementary library, `libradiate` [^2], from the same author of `libnet`, meant to build and write 802.11 frames, but it is not used by `packit`.

This could be an interesting feature to integrate. Unfortunately, at the moment we are trying to refactor the inherited codebase first, to make it easier to extend in the future, as it currently uses lots global variables, making it hard to reason about.  Of course, any PR to add this feature is welcome, even before we refactor the code!

> 
> Thank you very much in advance for your help.
> 

You're welcome! :)

Sincerely,

David

[^1]: http://packetfactory.openwall.net/projects/libradiate/802.11_toolkit-2.0.pdf
[^2]: https://nixbit.com/software/libradiate-review/

**Comment by dayrenefrometa** [comment]
Hi all,

First of all, thank you very much for your comments.

I am using the Atheros AR9285 WiFi chipset and the ath9k driver. I have checked this chipset supports packet injection, as you can see in the attached picture. In fact, packit works well when the interface is in Managed mode, but not in Monitor mode as I need.

For setting the interface in monitor mode I am using:

_ifconfig wlp2s0 down
iwconfig wlp2s0 mode monitor
ifconfig wlp2s0 up_

I have checked the interface actually goes into Monitor mode.

For invoking UDP packet injection I am using:

packit -m inject -t udp -s 192.168.1.149 -d 192.168.1.131 -S 403 -D 80 -c 100 -w 1 -b 1 -p 'this is my message'

When I try it in monitor mode, there is no error message, but I cannot receive the injected packets with Wireshark, as I can do when the interface is operating in Managed mode.

Please, let me know if you see anything wrong.

Thank you!

Best regards,

Dayrene

![PacketInjectioWorks](https://user-images.githubusercontent.com/68498451/140935254-a7f5f2ff-2215-48a2-9644-1c1996542f17.jpg)

**Comment by davidpolverari** [comment]
Hi Dayrene,

> I am using the Atheros AR9285 WiFi chipset and the ath9k driver. I have checked this chipset supports packet injection, as you can see in the attached picture. In fact, packit works well when the interface is in Managed mode, but not in Monitor mode as I need.

`packit` works well in that case because in managed mode the kernel + drivers are dealing with all 802.11 frame building and encapsulation, and `packit` only needs to worry about higher layer protocols. On the other hand, when operating in monitor mode, the OS will not build those frames. Anything the user-mode applications wants to inject when in monitor mode it will have to build and inject itself.

> For invoking UDP packet injection I am using:
> 
> packit -m inject -t udp -s 192.168.1.149 -d 192.168.1.131 -S 403 -D 80 -c 100 -w 1 -b 1 -p 'this is my message'
>
> When I try it in monitor mode, there is no error message, but I cannot receive the injected packets with Wireshark, as I can do when the interface is operating in Managed mode.

As I said on my previous comment on this issue, at the moment `packit` does not support building 802.11 frames (yet). This means that when in monitor mode, even when we have injection support, neither the OS nor `packit` will build the frames needed to encapsulate the IP/UDP payloads.
 
For your immediate use case, I would suggest you investigate using [Scapy](https://scapy.net/), a Python program/lib that allows you to construct and inject packets using almost any combination you want. You can use it interactively from the Python interpreter's REPL or 
from your script. For example, to connect to Google's primary DNS server, you could do the following:

```python
>>> packet = Ether()/IP(dst='8.8.8.8')/TCP(dport=53,flags='S')
>>> # below, the same example, but constructing each layer separately
>>> l2 = Ether()
>>> l3 = IP(dst='8.8.8.8/30')
>>> l4 = TCP(dport=53, flags = 'S')
>>> packet = l2/l3/l4
```
You could visit some the link below to have a glimpse of the its usage on wireless network packet injection:

https://research.securitum.com/generating-wifi-communication-in-scapy-tool/

Hope this will help you in the short term. Good luck!

Best regards,

David

**Comment by dayrenefrometa** [comment]
Hi David,

Thanks for the clarifications regarding Packit.

I was having a look at Scapy, and I think I can use it for what I need. Thanks a lot!

Best regards,

Dayrene
